### ISSUE TITLE
TCA-extended.ipynb not working

### ISSUE THREAD

**Issue by alexmaehon** [mohammadbashiri/tensor-decomposition-in-python#1]
This code has problem result whole notebook not working:
# Reconstruct M, with the result of each library
M_tl = reconstruct(factors_tl)
M_tt = reconstruct(factors_tt)

Error message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-87d78a910c1d> in <module>()
      1 # Reconstruct M, with the result of each library
----> 2 M_tl = reconstruct(factors_tl)
      3 M_tt = reconstruct(factors_tt)

/content/tensor-decomposition-in-python/utils.py in reconstruct(factors, rank)
     18 
     19 def reconstruct(factors, rank=None):
---> 20     a, b, c = factors
     21     rank = rank if rank else a.shape[1]
     22     R1s = np.zeros((a.shape[0], b.shape[0], c.shape[0], rank))

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by mohammadbashiri** [comment]
Thanks for pointing this out @alexmaehon.

The error is due to an updated version of Tensorly package. 

I have updated the readme and added the specific version of the Tensorly package that should be used. 
Also, I have added a Dockerfile that enables you to build a docker container within which you can run the notebook ([instructions](https://github.com/mohammadbashiri/tensor-decomposition-in-python#running-the-notebooks-inside-docker-container) in the readme file).

Addressed in https://github.com/mohammadbashiri/tensor-decomposition-in-python/commit/2577456e721a0fec6532a5b95e94e8410547a80e.
